name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: popovoleksandr/ipfs-pinata-deploy-action@v1
        with:
          pinata_api_key: ${{ secrets.PINATA_API_KEY }}
          pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}
          host_directory: './src'
          pinata_metadata: '{"name": "IPFS Demo Website"}'
