name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
          path: './src'
          verbose: true
          pin-name: 'IPFS Demo Website'
          remove-old: true
